name: Notify API Deployment & PR Repoerting

on:
  push:
    branches:
      - main
    paths:
      - 'notebooks/**'

jobs:
  notify_api_repository:
    name: "Notification to API Repository"
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Unit testing
        run: pytest

      - name: Deploy Stage
        uses: actions/github-script@v6
        with:
            github-token: ${{ secrets.ACCESS_TOKEN }}
            script: |
                await github.rest.actions.createWorkflowDispatch({
                    owner: "michelpf",
                    repo: "fiap-ds-mlops-api-laptop-pricing-brl",
                    workflow_id: "deploy.yml",
                    ref: "main"
                })